version: '3'

services:
  verfiy_api:
    restart: always
    build:
      context: .
      dockerfile: ./verifyservice/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      DEBUG: 'true'
    env_file:
      - .env
    command: uvicorn verifyservice.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - db

  verfiy_celery_worker:
    restart: always
    build:
      context: .
      dockerfile: ./verifyservice/Dockerfile
    env_file:
      - .env
    command: celery -A verifyservice.app.core.worker worker --loglevel=INFO
    depends_on:
      - verfiy_rabbitmq
      - redis

  verfiy_rabbitmq:
    image: rabbitmq:3.8.18-alpine
    ports:
    - "56721:5672"
    env_file:
      - .env

  selfservice_api:
    restart: always
    build:
      context: .
      dockerfile: ./selfservice/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/code
    environment:
      DEBUG: 'true'
    env_file:
      - .env
    command: uvicorn selfservice.app.main:app --reload --workers 1 --host 0.0.0.0 --port 9000
    depends_on:
      - db

  selfservice_celery_worker:
    restart: always
    build:
      context: .
      dockerfile: ./selfservice/Dockerfile
    env_file:
      - .env
    command: celery -A selfservice.app.core.worker worker --loglevel=INFO
    depends_on:
      - selfservice_rabbitmq
      - redis

  selfservice_rabbitmq:
    image: rabbitmq:3.8.18-alpine
    ports:
      - "56722:5672"
    env_file:
      - .env

  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASS}

  db:
    image: mongo:4.4.6
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: {}
